cs/IoC_MVC/Models/DevChrgTrackingService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IoC_MVC.Models
{
    public class DevChrgTrackingService : IDevChrgTrackingService
    {
        private IDeviceChargeRepository repository;

        public DevChrgTrackingService(IDeviceChargeRepository repository)
        {
            this.repository = repository;
        }

        public int TotalCharge
        {
            get { return repository.GetData(new DateTime().Date).TotalCharge; }
            set { repository.SetTotalCharge(new DateTime().Date, value); }
        }

        public int Capacity
        {
            get { return repository.GetData(new DateTime().Date).Capacity; }
            set { repository.SetCapacity(new DateTime().Date, value); }
        }

        public void ManuallyAddCharge(int amount)
        {
            TotalCharge += amount;
        }
    }
}

cs/IoC_MVC/Models/DeviceChargeData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IoC_MVC.Models
{
    public class DeviceChargeData
    {
        public int TotalCharge { get; set; }
        public int Capacity { get; set; }
    }
}

cs/IoC_MVC/Models/DeviceChargeRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IoC_MVC.Models
{
    public interface IDeviceChargeRepository
    {
        DeviceChargeData GetData(DateTime date);
        void SetTotalCharge(DateTime date, int value);
        void SetCapacity(DateTime date, int value);
    }
    public class DeviceChargeRepository : IDeviceChargeRepository
    {
        private static DeviceChargeData data = new DeviceChargeData();

        public DeviceChargeRepository()
        {
            data.Capacity = 100;
        }

        public DeviceChargeData GetData(DateTime date)
        {
            return data;
        }

        public void SetTotalCharge(DateTime date, int value)
        {
            data.TotalCharge = value;
        }

        public void SetCapacity(DateTime date, int value)
        {
            data.Capacity = value;
        }
    }
}

cs/IoC_MVC/Models/IDevChrgTrackingService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IoC_MVC.Models
{
    public interface IDevChrgTrackingService
    {
        int TotalCharge { get; set; }
        int Capacity { get; set; }
        void ManuallyAddCharge(int amount);
    }
}

cs/IoC_MVC/Controllers/DevChrgTrackingController.cs
using IoC_MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IoC_MVC.Controllers
{
    public class DevChrgTrackingController : Controller
    {

        private IDevChrgTrackingService devChrgTrackingService;

        public DevChrgTrackingController(IDevChrgTrackingService devChrgTrackingService)
        {
            this.devChrgTrackingService = devChrgTrackingService;
        }
        

        // GET: DevChrgTracking
        public ActionResult Index()
        {
            ViewBag.TotalCharge = devChrgTrackingService.TotalCharge;
            ViewBag.Capacity = devChrgTrackingService.Capacity;

            return View();
        }

        public ActionResult ManuallyAddCharge(int amount)
        {
            devChrgTrackingService.ManuallyAddCharge(amount);

            ViewBag.TotalCharge = devChrgTrackingService.TotalCharge;
            ViewBag.Capacity = devChrgTrackingService.Capacity;

            return View("Index");
        }
    }
}

cs/IoC_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IoC_MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

cs/IoC_MVC/Views/DevChrgTracking/Index.cshtml
@model IoC_MVC.Models.DevChrgTrackingService

@{
    ViewBag.Title = "Device Charging Tracker";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Device Charging Tracker</h2>
Total Charge: @ViewBag.TotalCharge
<p />
Capacity: @ViewBag.Capacity

@using (Html.BeginForm("ManuallyAddCharge", "DevChrgTracking"))
{
    <input type="text" name="amount" />
    <input type="submit" value="Add" />
}

cs/IoC_MVC/Views/Home/Index.cshtml
@model IoC_MVC.Models.DevChrgTrackingService

@{
    ViewBag.Title = "Device Charging Tracker";
    Layout = "../Shared/_Layout.cshtml";
}

<h2>Home</h2>
This landing page shows the MVC app is active and running.   Click on the "Device Charging Simulator" link above to test the IoC bits.

cs/IoC_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("IoC_MVC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Device Charging Simulator", "Index", "devChrgTracking")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - IoC_MVC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>